import { t, tc, sol } from './helpers.js'
// Tier 3-4: Binary Search, Sliding Window, Linked List, Trees
export const PROBLEMS_T3_T4 = [
  // ===== TIER 3: Binary Search (The Oracle's Library) =====
  { topic: 'binary-search', title: 'Binary Search', diff: 'easy', enemy: 'Page Wisp', tier: 3, order: 1, xp: 60, hp: 100,
    starter: t('function search(nums, target) {\n  \n}', 'def search(nums, target):\n    pass', 'class Solution {\n  public int search(int[] nums, int target) { return -1; }\n}', 'class Solution {\npublic:\n  int search(vector<int>& nums, int target) { return -1; }\n};'),
    tests: tc(['search([-1,0,3,5,9,12], 9)', '4'], ['search([-1,0,3,5,9,12], 2)', '-1']),
    solution: sol('function search(n,t){let l=0,r=n.length-1;while(l<=r){const m=Math.floor((l+r)/2);if(n[m]===t)return m;n[m]<t?l=m+1:r=m-1;}return-1;}') },
  { topic: 'binary-search', title: 'Search 2D Matrix', diff: 'easy', enemy: 'Tome Crawler', tier: 3, order: 2, xp: 60, hp: 100,
    starter: t('function searchMatrix(matrix, target) {\n  \n}', 'def search_matrix(matrix, target):\n    pass', 'class Solution {\n  public boolean searchMatrix(int[][] m, int t) { return false; }\n}', 'class Solution {\npublic:\n  bool searchMatrix(vector<vector<int>>& m, int t) { return false; }\n};'),
    tests: tc(['searchMatrix([[1,3,5,7],[10,11,16,20],[23,30,34,60]], 3)', 'true'], ['searchMatrix([[1,3,5,7],[10,11,16,20]], 13)', 'false']),
    solution: sol('function searchMatrix(m,t){let r=0,c=m[0].length-1;while(r<m.length&&c>=0){if(m[r][c]===t)return true;m[r][c]<t?r++:c--;}return false;}') },
  { topic: 'binary-search', title: 'Koko Eating Bananas', diff: 'medium', enemy: 'Librarian Specter', tier: 3, order: 3, xp: 100, hp: 160,
    starter: t('function minEatingSpeed(piles, h) {\n  \n}', 'def min_eating_speed(piles, h):\n    pass', 'class Solution {\n  public int minEatingSpeed(int[] piles, int h) { return 0; }\n}', 'class Solution {\npublic:\n  int minEatingSpeed(vector<int>& piles, int h) { return 0; }\n};'),
    tests: tc(['minEatingSpeed([3,6,7,11], 8)', '4'], ['minEatingSpeed([30,11,23,4,20], 5)', '30']),
    solution: sol('function minEatingSpeed(p,h){let l=1,r=Math.max(...p);while(l<r){const m=Math.floor((l+r)/2);p.reduce((s,x)=>s+Math.ceil(x/m),0)<=h?r=m:l=m+1;}return l;}') },
  { topic: 'binary-search', title: 'Find Min in Rotated Array', diff: 'medium', enemy: 'Scroll Wraith', tier: 3, order: 4, xp: 100, hp: 160,
    starter: t('function findMin(nums) {\n  \n}', 'def find_min(nums):\n    pass', 'class Solution {\n  public int findMin(int[] nums) { return 0; }\n}', 'class Solution {\npublic:\n  int findMin(vector<int>& nums) { return 0; }\n};'),
    tests: tc(['findMin([3,4,5,1,2])', '1'], ['findMin([4,5,6,7,0,1,2])', '0']),
    solution: sol('function findMin(n){let l=0,r=n.length-1;while(l<r){const m=Math.floor((l+r)/2);n[m]>n[r]?l=m+1:r=m;}return n[l];}') },
  { topic: 'binary-search', title: 'Median of Two Sorted Arrays', diff: 'boss', enemy: 'The Oracle', tier: 3, enemyTier: 5, order: 5, xp: 300, hp: 350,
    starter: t('function findMedian(nums1, nums2) {\n  \n}', 'def find_median(nums1, nums2):\n    pass', 'class Solution {\n  public double findMedian(int[] n1, int[] n2) { return 0; }\n}', 'class Solution {\npublic:\n  double findMedian(vector<int>& n1, vector<int>& n2) { return 0; }\n};'),
    tests: tc(['findMedian([1,3], [2])', '2'], ['findMedian([1,2], [3,4])', '2.5']),
    solution: sol('function findMedian(a,b){const m=[...a,...b].sort((x,y)=>x-y);const n=m.length;return n%2?m[Math.floor(n/2)]:(m[n/2-1]+m[n/2])/2;}') },

  // ===== TIER 3: Sliding Window (The Enchanted River) =====
  { topic: 'sliding-window', title: 'Best Time to Buy Stock', diff: 'easy', enemy: 'River Sprite', tier: 3, order: 1, xp: 60, hp: 100,
    starter: t('function maxProfit(prices) {\n  \n}', 'def max_profit(prices):\n    pass', 'class Solution {\n  public int maxProfit(int[] p) { return 0; }\n}', 'class Solution {\npublic:\n  int maxProfit(vector<int>& p) { return 0; }\n};'),
    tests: tc(['maxProfit([7,1,5,3,6,4])', '5'], ['maxProfit([7,6,4,3,1])', '0']),
    solution: sol('function maxProfit(p){let m=0,min=p[0];for(const x of p){min=Math.min(min,x);m=Math.max(m,x-min);}return m;}') },
  { topic: 'sliding-window', title: 'Longest Substring No Repeat', diff: 'easy', enemy: 'Current Eel', tier: 3, order: 2, xp: 60, hp: 100,
    starter: t('function lengthOfLongest(s) {\n  \n}', 'def length_of_longest(s):\n    pass', 'class Solution {\n  public int lengthOfLongest(String s) { return 0; }\n}', 'class Solution {\npublic:\n  int lengthOfLongest(string s) { return 0; }\n};'),
    tests: tc(['lengthOfLongest("abcabcbb")', '3'], ['lengthOfLongest("bbbbb")', '1']),
    solution: sol('function lengthOfLongest(s){const m=new Set();let l=0,r=0,mx=0;while(r<s.length){if(!m.has(s[r])){m.add(s[r++]);mx=Math.max(mx,m.size);}else m.delete(s[l++]);}return mx;}') },
  { topic: 'sliding-window', title: 'Longest Repeating Char Replacement', diff: 'medium', enemy: 'Tide Shapeshifter', tier: 3, order: 3, xp: 100, hp: 160,
    starter: t('function charReplacement(s, k) {\n  \n}', 'def char_replacement(s, k):\n    pass', 'class Solution {\n  public int charReplacement(String s, int k) { return 0; }\n}', 'class Solution {\npublic:\n  int charReplacement(string s, int k) { return 0; }\n};'),
    tests: tc(['charReplacement("ABAB", 2)', '4'], ['charReplacement("AABABBA", 1)', '4']),
    solution: sol('function charReplacement(s,k){const c={};let l=0,mx=0,res=0;for(let r=0;r<s.length;r++){c[s[r]]=(c[s[r]]||0)+1;mx=Math.max(mx,c[s[r]]);while(r-l+1-mx>k){c[s[l]]--;l++;}res=Math.max(res,r-l+1);}return res;}') },
  { topic: 'sliding-window', title: 'Permutation in String', diff: 'medium', enemy: 'Whirlpool Djinn', tier: 3, order: 4, xp: 100, hp: 160,
    starter: t('function checkInclusion(s1, s2) {\n  \n}', 'def check_inclusion(s1, s2):\n    pass', 'class Solution {\n  public boolean checkInclusion(String s1, String s2) { return false; }\n}', 'class Solution {\npublic:\n  bool checkInclusion(string s1, string s2) { return false; }\n};'),
    tests: tc(['checkInclusion("ab", "eidbaooo")', 'true'], ['checkInclusion("ab", "eidboaoo")', 'false']),
    solution: sol('function checkInclusion(s1,s2){if(s1.length>s2.length)return false;const c1=Array(26).fill(0),c2=Array(26).fill(0);for(let i=0;i<s1.length;i++){c1[s1.charCodeAt(i)-97]++;c2[s2.charCodeAt(i)-97]++;}for(let i=0;i<s2.length-s1.length;i++){if(c1.join()===c2.join())return true;c2[s2.charCodeAt(i+s1.length)-97]++;c2[s2.charCodeAt(i)-97]--;}return c1.join()===c2.join();}') },
  { topic: 'sliding-window', title: 'Minimum Window Substring', diff: 'boss', enemy: 'The River Leviathan', tier: 3, enemyTier: 6, order: 5, xp: 300, hp: 350,
    starter: t('function minWindow(s, t) {\n  \n}', 'def min_window(s, t):\n    pass', 'class Solution {\n  public String minWindow(String s, String t) { return ""; }\n}', 'class Solution {\npublic:\n  string minWindow(string s, string t) { return ""; }\n};'),
    tests: tc(['minWindow("ADOBECODEBANC", "ABC")', '"BANC"']),
    solution: sol('function minWindow(s,t){const need={};for(const c of t)need[c]=(need[c]||0)+1;let l=0,cnt=t.length,res="",min=Infinity;for(let r=0;r<s.length;r++){if(need[s[r]]-->0)cnt--;while(!cnt){if(r-l+1<min){min=r-l+1;res=s.slice(l,r+1);}if(++need[s[l++]]>0)cnt++;}}return res;}') },

  // ===== TIER 3: Linked List (The Chain Depths) =====
  { topic: 'linked-list', title: 'Reverse Linked List', diff: 'easy', enemy: 'Chain Imp', tier: 3, order: 1, xp: 60, hp: 100,
    starter: t('function reverseList(head) {\n  // head = { val, next }\n}', 'def reverse_list(head):\n    pass', 'class Solution {\n  public ListNode reverseList(ListNode head) { return null; }\n}', 'class Solution {\npublic:\n  ListNode* reverseList(ListNode* head) { return nullptr; }\n};'),
    tests: tc(['reverseList([1,2,3,4,5])', '[5,4,3,2,1]']),
    solution: sol('function reverseList(h){let p=null;while(h){const n=h.next;h.next=p;p=h;h=n;}return p;}') },
  { topic: 'linked-list', title: 'Merge Two Sorted Lists', diff: 'easy', enemy: 'Link Serpent', tier: 3, order: 2, xp: 60, hp: 100,
    starter: t('function mergeTwoLists(l1, l2) {\n  \n}', 'def merge_two_lists(l1, l2):\n    pass', 'class Solution {\n  public ListNode mergeTwoLists(ListNode l1, ListNode l2) { return null; }\n}', 'class Solution {\npublic:\n  ListNode* mergeTwoLists(ListNode* l1, ListNode* l2) { return nullptr; }\n};'),
    tests: tc(['mergeTwoLists([1,2,4], [1,3,4])', '[1,1,2,3,4,4]']),
    solution: sol('function mergeTwoLists(a,b){if(!a)return b;if(!b)return a;if(a.val<b.val){a.next=mergeTwoLists(a.next,b);return a;}b.next=mergeTwoLists(a,b.next);return b;}') },
  { topic: 'linked-list', title: 'Reorder List', diff: 'medium', enemy: 'Shackle Phantom', tier: 3, order: 3, xp: 100, hp: 160,
    starter: t('function reorderList(head) {\n  \n}', 'def reorder_list(head):\n    pass', 'class Solution {\n  public void reorderList(ListNode head) {}\n}', 'class Solution {\npublic:\n  void reorderList(ListNode* head) {}\n};'),
    tests: tc(['reorderList([1,2,3,4])', '[1,4,2,3]']),
    solution: sol('function reorderList(h){if(!h)return;let s=h,f=h;while(f.next&&f.next.next){s=s.next;f=f.next.next;}let p=null,c=s.next;s.next=null;while(c){const n=c.next;c.next=p;p=c;c=n;}let a=h;while(p){const t1=a.next,t2=p.next;a.next=p;p.next=t1;a=t1;p=t2;}}') },
  { topic: 'linked-list', title: 'Remove Nth From End', diff: 'medium', enemy: 'Iron Wraith', tier: 3, order: 4, xp: 100, hp: 160,
    starter: t('function removeNthFromEnd(head, n) {\n  \n}', 'def remove_nth(head, n):\n    pass', 'class Solution {\n  public ListNode removeNth(ListNode head, int n) { return null; }\n}', 'class Solution {\npublic:\n  ListNode* removeNth(ListNode* head, int n) { return nullptr; }\n};'),
    tests: tc(['removeNthFromEnd([1,2,3,4,5], 2)', '[1,2,3,5]']),
    solution: sol('function removeNthFromEnd(h,n){const d={val:0,next:h};let f=d,s=d;for(let i=0;i<=n;i++)f=f.next;while(f){f=f.next;s=s.next;}s.next=s.next.next;return d.next;}') },
  { topic: 'linked-list', title: 'Merge K Sorted Lists', diff: 'boss', enemy: 'The Chain Colossus', tier: 3, enemyTier: 7, order: 5, xp: 300, hp: 350,
    starter: t('function mergeKLists(lists) {\n  \n}', 'def merge_k_lists(lists):\n    pass', 'class Solution {\n  public ListNode mergeKLists(ListNode[] lists) { return null; }\n}', 'class Solution {\npublic:\n  ListNode* mergeKLists(vector<ListNode*>& lists) { return nullptr; }\n};'),
    tests: tc(['mergeKLists([[1,4,5],[1,3,4],[2,6]])', '[1,1,2,3,4,4,5,6]']),
    solution: sol('function mergeKLists(ls){if(!ls.length)return null;while(ls.length>1){const m=[];for(let i=0;i<ls.length;i+=2){const a=ls[i],b=ls[i+1]||null;m.push(merge(a,b));}ls=m;}return ls[0];function merge(a,b){if(!a)return b;if(!b)return a;if(a.val<b.val){a.next=merge(a.next,b);return a;}b.next=merge(a,b.next);return b;}}') },

  // ===== TIER 4: Trees (The Elder Grove) =====
  { topic: 'trees', title: 'Invert Binary Tree', diff: 'easy', enemy: 'Twig Sprite', tier: 4, order: 1, xp: 60, hp: 120,
    starter: t('function invertTree(root) {\n  \n}', 'def invert_tree(root):\n    pass', 'class Solution {\n  public TreeNode invertTree(TreeNode root) { return null; }\n}', 'class Solution {\npublic:\n  TreeNode* invertTree(TreeNode* root) { return nullptr; }\n};'),
    tests: tc(['invertTree([4,2,7,1,3,6,9])', '[4,7,2,9,6,3,1]']),
    solution: sol('function invertTree(r){if(!r)return null;[r.left,r.right]=[invertTree(r.right),invertTree(r.left)];return r;}') },
  { topic: 'trees', title: 'Max Depth of Binary Tree', diff: 'easy', enemy: 'Moss Goblin', tier: 4, order: 2, xp: 60, hp: 120,
    starter: t('function maxDepth(root) {\n  \n}', 'def max_depth(root):\n    pass', 'class Solution {\n  public int maxDepth(TreeNode root) { return 0; }\n}', 'class Solution {\npublic:\n  int maxDepth(TreeNode* root) { return 0; }\n};'),
    tests: tc(['maxDepth([3,9,20,null,null,15,7])', '3']),
    solution: sol('function maxDepth(r){if(!r)return 0;return 1+Math.max(maxDepth(r.left),maxDepth(r.right));}') },
  { topic: 'trees', title: 'Lowest Common Ancestor', diff: 'medium', enemy: 'Bark Guardian', tier: 4, order: 3, xp: 100, hp: 180,
    starter: t('function lowestCommonAncestor(root, p, q) {\n  \n}', 'def lca(root, p, q):\n    pass', 'class Solution {\n  public TreeNode lca(TreeNode root, TreeNode p, TreeNode q) { return null; }\n}', 'class Solution {\npublic:\n  TreeNode* lca(TreeNode* root, TreeNode* p, TreeNode* q) { return nullptr; }\n};'),
    tests: tc(['lowestCommonAncestor([6,2,8,0,4,7,9], 2, 8)', '6']),
    solution: sol('function lowestCommonAncestor(r,p,q){if(!r||r===p||r===q)return r;const l=lowestCommonAncestor(r.left,p,q);const ri=lowestCommonAncestor(r.right,p,q);return l&&ri?r:l||ri;}') },
  { topic: 'trees', title: 'Binary Tree Level Order', diff: 'medium', enemy: 'Canopy Wraith', tier: 4, order: 4, xp: 100, hp: 180,
    starter: t('function levelOrder(root) {\n  \n}', 'def level_order(root):\n    pass', 'class Solution {\n  public List<List<Integer>> levelOrder(TreeNode root) { return new ArrayList<>(); }\n}', 'class Solution {\npublic:\n  vector<vector<int>> levelOrder(TreeNode* root) { return {}; }\n};'),
    tests: tc(['levelOrder([3,9,20,null,null,15,7])', '[[3],[9,20],[15,7]]']),
    solution: sol('function levelOrder(r){if(!r)return[];const q=[r],res=[];while(q.length){const lvl=[];const n=q.length;for(let i=0;i<n;i++){const node=q.shift();lvl.push(node.val);if(node.left)q.push(node.left);if(node.right)q.push(node.right);}res.push(lvl);}return res;}') },
  { topic: 'trees', title: 'Serialize & Deserialize Tree', diff: 'boss', enemy: 'The Ancient Treant', tier: 4, enemyTier: 2, order: 5, xp: 300, hp: 400,
    starter: t('function serialize(root) {\n  \n}\nfunction deserialize(data) {\n  \n}', 'def serialize(root):\n    pass\ndef deserialize(data):\n    pass', 'public class Codec {\n  public String serialize(TreeNode root) { return ""; }\n  public TreeNode deserialize(String data) { return null; }\n}', 'class Codec {\npublic:\n  string serialize(TreeNode* root) { return ""; }\n  TreeNode* deserialize(string data) { return nullptr; }\n};'),
    tests: tc(['deserialize(serialize([1,2,3,null,null,4,5]))', '[1,2,3,null,null,4,5]']),
    solution: sol('function serialize(r){if(!r)return"null";return r.val+","+serialize(r.left)+","+serialize(r.right);}function deserialize(d){const a=d.split(",");let i=0;function build(){if(a[i]==="null"){i++;return null;}const n={val:+a[i++]};n.left=build();n.right=build();return n;}return build();}') },
]
