import { t, tc, sol } from './helpers.js'
// Tier 1-2 problems. Each topic: 2 easy, 2 medium, 1 boss
export const PROBLEMS_T1_T2 = [
  // ===== TIER 1: Arrays & Hashing (The Crystal Caverns) =====
  { topic: 'arrays-hashing', title: 'Two Sum', diff: 'easy', enemy: 'Cave Sprite', tier: 1, order: 1, xp: 50, hp: 80,
    starter: t('function twoSum(nums, target) {\n  // return indices\n}', 'def two_sum(nums, target):\n    pass', 'class Solution {\n  public int[] twoSum(int[] nums, int target) {\n    return new int[]{};\n  }\n}', 'class Solution {\npublic:\n  vector<int> twoSum(vector<int>& nums, int target) {\n    return {};\n  }\n};'),
    tests: tc(['twoSum([2,7,11,15], 9)', '[0,1]'], ['twoSum([3,2,4], 6)', '[1,2]']),
    solution: sol('function twoSum(nums, t) {\n  const m = {};\n  for (let i = 0; i < nums.length; i++) {\n    if (m[t - nums[i]] !== undefined) return [m[t-nums[i]], i];\n    m[nums[i]] = i;\n  }\n}') },
  { topic: 'arrays-hashing', title: 'Contains Duplicate', diff: 'easy', enemy: 'Crystal Bat', tier: 1, order: 2, xp: 50, hp: 80,
    starter: t('function containsDup(nums) {\n  \n}', 'def contains_dup(nums):\n    pass', 'class Solution {\n  public boolean containsDup(int[] nums) {\n    return false;\n  }\n}', 'class Solution {\npublic:\n  bool containsDup(vector<int>& nums) {\n    return false;\n  }\n};'),
    tests: tc(['containsDup([1,2,3,1])', 'true'], ['containsDup([1,2,3])', 'false']),
    solution: sol('function containsDup(n) { return new Set(n).size !== n.length; }') },
  { topic: 'arrays-hashing', title: 'Valid Anagram', diff: 'medium', enemy: 'Gem Golem', tier: 1, order: 3, xp: 80, hp: 120,
    starter: t('function isAnagram(s, t) {\n  \n}', 'def is_anagram(s, t):\n    pass', 'class Solution {\n  public boolean isAnagram(String s, String t) {\n    return false;\n  }\n}', 'class Solution {\npublic:\n  bool isAnagram(string s, string t) {\n    return false;\n  }\n};'),
    tests: tc(['isAnagram("anagram","nagaram")', 'true'], ['isAnagram("rat","car")', 'false']),
    solution: sol('function isAnagram(s,t) { return s.split("").sort().join("") === t.split("").sort().join(""); }') },
  { topic: 'arrays-hashing', title: 'Group Anagrams', diff: 'medium', enemy: 'Quartz Elemental', tier: 1, order: 4, xp: 100, hp: 150,
    starter: t('function groupAnagrams(strs) {\n  \n}', 'def group_anagrams(strs):\n    pass', 'class Solution {\n  public List<List<String>> groupAnagrams(String[] strs) {\n    return new ArrayList<>();\n  }\n}', 'class Solution {\npublic:\n  vector<vector<string>> groupAnagrams(vector<string>& strs) {\n    return {};\n  }\n};'),
    tests: tc(['groupAnagrams(["eat","tea","tan","ate","nat","bat"]).length', '3']),
    solution: sol('function groupAnagrams(s) { const m={}; for(const w of s){const k=[...w].sort().join(""); (m[k]=m[k]||[]).push(w);} return Object.values(m); }') },
  { topic: 'arrays-hashing', title: 'Top K Frequent Elements', diff: 'boss', enemy: 'Crystal Guardian', tier: 1, enemyTier: 5, order: 5, xp: 200, hp: 250,
    starter: t('function topKFrequent(nums, k) {\n  \n}', 'def top_k_frequent(nums, k):\n    pass', 'class Solution {\n  public int[] topKFrequent(int[] nums, int k) {\n    return new int[]{};\n  }\n}', 'class Solution {\npublic:\n  vector<int> topKFrequent(vector<int>& nums, int k) {\n    return {};\n  }\n};'),
    tests: tc(['topKFrequent([1,1,1,2,2,3], 2).sort()', '[1,2]']),
    solution: sol('function topKFrequent(n,k){const m={};for(const x of n)m[x]=(m[x]||0)+1;return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,k).map(e=>+e[0]);}') },

  // ===== TIER 2: Two Pointers (The Mirror Halls) =====
  { topic: 'two-pointers', title: 'Valid Palindrome', diff: 'easy', enemy: 'Mirror Wisp', tier: 2, order: 1, xp: 50, hp: 100,
    starter: t('function isPalindrome(s) {\n  \n}', 'def is_palindrome(s):\n    pass', 'class Solution {\n  public boolean isPalindrome(String s) {\n    return false;\n  }\n}', 'class Solution {\npublic:\n  bool isPalindrome(string s) {\n    return false;\n  }\n};'),
    tests: tc(['isPalindrome("A man, a plan, a canal: Panama")', 'true'], ['isPalindrome("race a car")', 'false']),
    solution: sol('function isPalindrome(s){const c=s.toLowerCase().replace(/[^a-z0-9]/g,"");return c===c.split("").reverse().join("");}') },
  { topic: 'two-pointers', title: 'Two Sum II', diff: 'easy', enemy: 'Echo Shade', tier: 2, order: 2, xp: 50, hp: 100,
    starter: t('function twoSum2(nums, target) {\n  \n}', 'def two_sum_2(nums, target):\n    pass', 'class Solution {\n  public int[] twoSum(int[] nums, int target) {\n    return new int[]{};\n  }\n}', 'class Solution {\npublic:\n  vector<int> twoSum(vector<int>& nums, int target) {\n    return {};\n  }\n};'),
    tests: tc(['twoSum2([2,7,11,15], 9)', '[1,2]'], ['twoSum2([2,3,4], 6)', '[1,3]']),
    solution: sol('function twoSum2(n,t){let l=0,r=n.length-1;while(l<r){const s=n[l]+n[r];if(s===t)return[l+1,r+1];s<t?l++:r--;}return[];}') },
  { topic: 'two-pointers', title: '3Sum', diff: 'medium', enemy: 'Prism Knight', tier: 2, order: 3, xp: 100, hp: 150,
    starter: t('function threeSum(nums) {\n  \n}', 'def three_sum(nums):\n    pass', 'class Solution {\n  public List<List<Integer>> threeSum(int[] nums) {\n    return new ArrayList<>();\n  }\n}', 'class Solution {\npublic:\n  vector<vector<int>> threeSum(vector<int>& nums) {\n    return {};\n  }\n};'),
    tests: tc(['threeSum([-1,0,1,2,-1,-4]).length', '2']),
    solution: sol('function threeSum(n){n.sort((a,b)=>a-b);const r=[];for(let i=0;i<n.length-2;i++){if(i>0&&n[i]===n[i-1])continue;let l=i+1,h=n.length-1;while(l<h){const s=n[i]+n[l]+n[h];if(s===0){r.push([n[i],n[l],n[h]]);while(n[l]===n[++l]);while(n[h]===n[--h]);}else s<0?l++:h--;}}return r;}') },
  { topic: 'two-pointers', title: 'Container With Most Water', diff: 'medium', enemy: 'Reflection Demon', tier: 2, order: 4, xp: 100, hp: 150,
    starter: t('function maxArea(height) {\n  \n}', 'def max_area(height):\n    pass', 'class Solution {\n  public int maxArea(int[] height) {\n    return 0;\n  }\n}', 'class Solution {\npublic:\n  int maxArea(vector<int>& height) {\n    return 0;\n  }\n};'),
    tests: tc(['maxArea([1,8,6,2,5,4,8,3,7])', '49']),
    solution: sol('function maxArea(h){let l=0,r=h.length-1,m=0;while(l<r){m=Math.max(m,Math.min(h[l],h[r])*(r-l));h[l]<h[r]?l++:r--;}return m;}') },
  { topic: 'two-pointers', title: 'Trapping Rain Water', diff: 'boss', enemy: 'The Doppelganger', tier: 2, enemyTier: 3, order: 5, xp: 250, hp: 300,
    starter: t('function trap(height) {\n  \n}', 'def trap(height):\n    pass', 'class Solution {\n  public int trap(int[] height) {\n    return 0;\n  }\n}', 'class Solution {\npublic:\n  int trap(vector<int>& height) {\n    return 0;\n  }\n};'),
    tests: tc(['trap([0,1,0,2,1,0,1,3,2,1,2,1])', '6'], ['trap([4,2,0,3,2,5])', '9']),
    solution: sol('function trap(h){let l=0,r=h.length-1,lm=0,rm=0,w=0;while(l<r){if(h[l]<h[r]){h[l]>=lm?lm=h[l]:w+=lm-h[l];l++;}else{h[r]>=rm?rm=h[r]:w+=rm-h[r];r--;}}return w;}') },

  // ===== TIER 2: Stack (The Iron Citadel) =====
  { topic: 'stack', title: 'Valid Parentheses', diff: 'easy', enemy: 'Iron Sentry', tier: 2, order: 1, xp: 50, hp: 100,
    starter: t('function isValid(s) {\n  \n}', 'def is_valid(s):\n    pass', 'class Solution {\n  public boolean isValid(String s) {\n    return false;\n  }\n}', 'class Solution {\npublic:\n  bool isValid(string s) {\n    return false;\n  }\n};'),
    tests: tc(['isValid("()")', 'true'], ['isValid("([)]")', 'false'], ['isValid("{[]}")', 'true']),
    solution: sol('function isValid(s){const st=[],m={"(":")","{":"}","[":"]"};for(const c of s){if(m[c])st.push(m[c]);else if(st.pop()!==c)return false;}return!st.length;}') },
  { topic: 'stack', title: 'Min Stack', diff: 'easy', enemy: 'Gear Goblin', tier: 2, order: 2, xp: 60, hp: 100,
    starter: t('class MinStack {\n  constructor() { this.s=[]; this.m=[]; }\n  push(v) {}\n  pop() {}\n  top() {}\n  getMin() {}\n}', 'class MinStack:\n    def __init__(self):\n        self.s=[]\n        self.m=[]\n    def push(self,v): pass\n    def pop(self): pass\n    def top(self): pass\n    def getMin(self): pass', 'class MinStack {\n  Stack<Integer> s=new Stack<>();\n  Stack<Integer> m=new Stack<>();\n  public void push(int v){}\n  public void pop(){}\n  public int top(){return 0;}\n  public int getMin(){return 0;}\n}', 'class MinStack{\n  stack<int> s,m;\npublic:\n  void push(int v){}\n  void pop(){}\n  int top(){return 0;}\n  int getMin(){return 0;}\n};'),
    tests: tc(['(() => { const s=new MinStack(); s.push(-2); s.push(0); s.push(-3); return s.getMin(); })()', '-3']),
    solution: sol('class MinStack{constructor(){this.s=[];this.m=[];}push(v){this.s.push(v);this.m.push(Math.min(v,this.m.length?this.m[this.m.length-1]:v));}pop(){this.s.pop();this.m.pop();}top(){return this.s[this.s.length-1];}getMin(){return this.m[this.m.length-1];}}') },
  { topic: 'stack', title: 'Evaluate RPN', diff: 'medium', enemy: 'Clockwork Mage', tier: 2, order: 3, xp: 100, hp: 150,
    starter: t('function evalRPN(tokens) {\n  \n}', 'def eval_rpn(tokens):\n    pass', 'class Solution {\n  public int evalRPN(String[] tokens) {\n    return 0;\n  }\n}', 'class Solution {\npublic:\n  int evalRPN(vector<string>& tokens) {\n    return 0;\n  }\n};'),
    tests: tc(['evalRPN(["2","1","+","3","*"])', '9'], ['evalRPN(["4","13","5","/","+"])', '6']),
    solution: sol('function evalRPN(t){const s=[];for(const x of t){if("+-*/".includes(x)){const b=s.pop(),a=s.pop();s.push(x==="+"?a+b:x==="-"?a-b:x==="*"?a*b:Math.trunc(a/b));}else s.push(+x);}return s[0];}') },
  { topic: 'stack', title: 'Daily Temperatures', diff: 'medium', enemy: 'Steam Phantom', tier: 2, order: 4, xp: 100, hp: 150,
    starter: t('function dailyTemps(temps) {\n  \n}', 'def daily_temps(temps):\n    pass', 'class Solution {\n  public int[] dailyTemps(int[] temps) {\n    return new int[]{};\n  }\n}', 'class Solution {\npublic:\n  vector<int> dailyTemps(vector<int>& temps) {\n    return {};\n  }\n};'),
    tests: tc(['dailyTemps([73,74,75,71,69,72,76,73])', '[1,1,4,2,1,1,0,0]']),
    solution: sol('function dailyTemps(t){const r=Array(t.length).fill(0),s=[];for(let i=0;i<t.length;i++){while(s.length&&t[i]>t[s[s.length-1]]){const j=s.pop();r[j]=i-j;}s.push(i);}return r;}') },
  { topic: 'stack', title: 'Largest Rectangle in Histogram', diff: 'boss', enemy: 'The Iron Titan', tier: 2, enemyTier: 4, order: 5, xp: 250, hp: 300,
    starter: t('function largestRect(heights) {\n  \n}', 'def largest_rect(heights):\n    pass', 'class Solution {\n  public int largestRect(int[] heights) {\n    return 0;\n  }\n}', 'class Solution {\npublic:\n  int largestRect(vector<int>& heights) {\n    return 0;\n  }\n};'),
    tests: tc(['largestRect([2,1,5,6,2,3])', '10'], ['largestRect([2,4])', '4']),
    solution: sol('function largestRect(h){const s=[];let m=0;h.push(0);for(let i=0;i<h.length;i++){while(s.length&&h[i]<h[s[s.length-1]]){const height=h[s.pop()];const w=s.length?i-s[s.length-1]-1:i;m=Math.max(m,height*w);}s.push(i);}return m;}') },
]
